@startuml

class Form {
    - String archivoClavesNombre;
    - String archivoMensajeNombre;
    + constructor();
    - subirArchivoClavesBoton()
    - subirArchivoMensajeBoton()
    - encriptarDesencriptarBoton()
    - salirBoton();
}

class ControladorVista{
    - File archivo
    + String mostrarTextoEncriptado()
    + String mostrarTextoDesencriptado()
    - String importarTextoEncriptado()
    - String importarTextoDesencriptado()

}
class RSA {
    - Clave clavesPublicaPrivada;
    - Mensaje mensaje;
    + constructor(Clave claves, Mensaje mensaje)
    + String encriptar()
    + String desencriptar()
}

class Mensaje{
    - String texto;
    + constructor(String texto)
    + Byte[] getMensajeParaEncriptarEnBytes()
    + Byte[] getMensajeParaDesencriptarEnBytes()
}

class Clave{
    - XmlNode claves;
    + constructor(XmlDocument archivo)
    + String getClavePublica()
    + String getClavePrivada()
    - XmlNode getClavesFromXml()
}

Form <-- ControladorVista
RSA <.u. ControladorVista : use
Clave -u-> RSA
Mensaje -u-> RSA
@enduml