@startuml

class ControladorVista{
    - File archivo
    + seleccionarClaves()
    + mostrarClaves()
    + mostrarTextoEncriptado()
    + mostrarTextoDesencriptado()
    - importarTextoEncriptado()
    - importarTextoDesencriptado()

}
class RSA {
    - Clave clavesPublicaPrivada;
    - Mensaje mensaje;
    + constructor(Clave claves, Mensaje mensaje)
    + encriptar()
    + desencriptar()
}

class Mensaje{
    - String texto;
    + constructor(String texto)
    + Byte[] getMensajeEnBytes()
}

class Clave{
    - XmlNode claves;
    + constructor(File archivo)
    + String getClavePublica()
    + String getClavePrivada()
    - getValorFromFile()
}

ControladorVista ..> RSA : uses
Clave -u-> RSA
Mensaje -u-> RSA
@enduml